"use client";

import * as React from "react";
import {
  Layers,
  Code,
  Sparkles,
  MousePointerClick,
  Award,
  FileText,
  ShieldCheck,
  Eye
} from "lucide-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { VariablePlayground } from "../variable-playground";

export function TemplatesSection() {
  return (
    <div className="space-y-8">
      <div>
        <div className="flex items-center gap-2 mb-2">
          <span className="text-[11px] font-mono uppercase tracking-wider text-purple-400 font-bold px-2 py-0.5 rounded bg-purple-500/10 border border-purple-500/20">
            Studio & Content
          </span>
          <span className="text-xs text-zinc-500">•</span>
          <span className="text-xs text-zinc-400">Design</span>
        </div>
        <h1 className="text-3xl font-extrabold text-white tracking-tight">HTML & Visual Templates</h1>
        <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
          The Postly Template Studio at <code>/templates</code> provides a dual-mode canvas: visual WYSIWYG editing for marketing and raw HTML code editing for pixel-perfect transactional emails.
        </p>
      </div>

      <div className="h-px bg-zinc-800/80" />

      {/* Editor Modes */}
      <section id="editor-modes" className="space-y-4 scroll-mt-24">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <Layers className="h-5 w-5 text-primary" />
          Dual Editor Modes: Visual vs HTML
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="rounded-xl border border-zinc-800 bg-zinc-950 p-4 space-y-2">
            <span className="font-bold text-white text-sm">Visual Mode (TipTap)</span>
            <p className="text-zinc-400 leading-relaxed">
              Rich-text editing with bold, italics, alignments, image embeds, custom colors, and one-click Tracked Button insertion. Generates clean inline-styled HTML behind the scenes.
            </p>
          </div>
          <div className="rounded-xl border border-zinc-800 bg-zinc-950 p-4 space-y-2">
            <span className="font-bold text-white text-sm">HTML Code Mode (CodeMirror)</span>
            <p className="text-zinc-400 leading-relaxed">
              Full access to the raw DOM. Paste production HTML templates generated by MJML, Stripo, or Figma. Features syntax highlighting and auto-closing tags.
            </p>
          </div>
        </div>
      </section>

      {/* Email Client Compatibility */}
      <section id="email-client-compat" className="space-y-4 scroll-mt-24">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <ShieldCheck className="h-5 w-5 text-primary" />
          Email Client Rendering Rules
        </h2>
        <p className="text-sm text-zinc-300 leading-relaxed">
          Email rendering engines (especially Microsoft Outlook and Gmail for Android) have strict CSS limitations. To ensure bulletproof cross-client rendering:
        </p>
        <ul className="space-y-2 text-xs text-zinc-400 pl-4 list-disc">
          <li><strong>Inline CSS:</strong> Always use inline styles (<code>style=&quot;...&quot;</code>) rather than external CSS stylesheets.</li>
          <li><strong>Table-based Layouts:</strong> Use HTML tables for multi-column structures to support legacy Outlook MSO rendering.</li>
          <li><strong>Images:</strong> Always declare explicit <code>width</code>, <code>height</code>, and <code>alt</code> attributes.</li>
        </ul>
      </section>

      {/* Responsive Preview */}
      <section id="responsive-preview" className="space-y-4 scroll-mt-24">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <Eye className="h-5 w-5 text-emerald-400" />
          Mobile vs Desktop Live Preview
        </h2>
        <p className="text-sm text-zinc-300 leading-relaxed">
          The Template Studio includes an interactive device toggle (Desktop 600px vs Mobile 375px) that instantly re-renders your template inside an isolated iframe, allowing you to catch media query failures before launching a bulk campaign.
        </p>
      </section>
    </div>
  );
}

export function VariablesSection() {
  return (
    <div className="space-y-8">
      <div>
        <div className="flex items-center gap-2 mb-2">
          <span className="text-[11px] font-mono uppercase tracking-wider text-purple-400 font-bold px-2 py-0.5 rounded bg-purple-500/10 border border-purple-500/20">
            Studio & Content
          </span>
          <span className="text-xs text-zinc-500">•</span>
          <span className="text-xs text-zinc-400">Syntax & Tags</span>
        </div>
        <h1 className="text-3xl font-extrabold text-white tracking-tight">Merge Tags & Variables</h1>
        <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
          Postly uses Handlebars-style double curly braces <code>{"{{variable_name}}"}</code> to substitute personalized values at dispatch time.
        </p>
      </div>

      <div className="h-px bg-zinc-800/80" />

      {/* Syntax Table */}
      <section id="variable-syntax" className="space-y-4 scroll-mt-24">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <Code className="h-5 w-5 text-primary" />
          Variable Syntax & Notation
        </h2>
        <div className="rounded-xl border border-zinc-800 overflow-hidden bg-zinc-950">
          <Table>
            <TableHeader className="bg-zinc-900/60">
              <TableRow className="border-zinc-800">
                <TableHead className="text-zinc-300 font-bold">Tag Format</TableHead>
                <TableHead className="text-zinc-300 font-bold">Description</TableHead>
                <TableHead className="text-zinc-300 font-bold">Example Output</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow className="border-zinc-800/60">
                <TableCell className="font-mono text-xs text-primary">{"{{name}}"}</TableCell>
                <TableCell className="text-xs text-zinc-400">Matches the &lsquo;name&rsquo; column in your CSV upload or compose form</TableCell>
                <TableCell className="text-xs text-white">Alex Rivera</TableCell>
              </TableRow>
              <TableRow className="border-zinc-800/60">
                <TableCell className="font-mono text-xs text-primary">{"{{email}}"}</TableCell>
                <TableCell className="text-xs text-zinc-400">Reserved recipient email address</TableCell>
                <TableCell className="text-xs text-white">alex@company.org</TableCell>
              </TableRow>
              <TableRow className="border-zinc-800/60">
                <TableCell className="font-mono text-xs text-primary">{"{{QR_CODE}}"}</TableCell>
                <TableCell className="text-xs text-zinc-400">Generates unique recipient check-in QR code inline image</TableCell>
                <TableCell className="text-xs text-emerald-400 font-mono">&lt;img src=&quot;...&quot; /&gt;</TableCell>
              </TableRow>
              <TableRow className="border-zinc-800/60">
                <TableCell className="font-mono text-xs text-primary">{"{{TRACKED_URL:label:url}}"}</TableCell>
                <TableCell className="text-xs text-zinc-400">Rewrites destination URL to a click-tracking proxy redirect</TableCell>
                <TableCell className="text-xs text-blue-400 font-mono">https://postly.../click/...</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </section>

      {/* Interactive Variable Playground */}
      <section id="interactive-playground" className="space-y-4 scroll-mt-24">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-amber-400" />
          Interactive Merge Tag Playground
        </h2>
        <VariablePlayground />
      </section>
    </div>
  );
}

export function ClickTrackingSection() {
  return (
    <div className="space-y-8">
      <div>
        <div className="flex items-center gap-2 mb-2">
          <span className="text-[11px] font-mono uppercase tracking-wider text-purple-400 font-bold px-2 py-0.5 rounded bg-purple-500/10 border border-purple-500/20">
            Studio & Content
          </span>
          <span className="text-xs text-zinc-500">•</span>
          <span className="text-xs text-zinc-400">Attribution</span>
        </div>
        <h1 className="text-3xl font-extrabold text-white tracking-tight">Click Tracking & Buttons</h1>
        <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
          Measure campaign conversion and CTA engagement with signed click-tracking redirects, per-button attribution, and device parsing.
        </p>
      </div>

      <div className="h-px bg-zinc-800/80" />

      {/* How Tracking Works */}
      <section id="how-tracking-works" className="space-y-4 scroll-mt-24">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <MousePointerClick className="h-5 w-5 text-primary" />
          How Click Tracking Works
        </h2>
        <p className="text-sm text-zinc-300 leading-relaxed">
          When an email is dispatched, Postly intercepts all <code>{"{{TRACKED_URL:label:destination}}"}</code> tags and rewrites them into secure, encrypted redirect links:
        </p>
        <div className="rounded-lg border border-zinc-800 bg-zinc-950 p-4 font-mono text-xs text-primary leading-relaxed overflow-x-auto">
          https://postly.gowreesh.me/api/track/click/{'{emailId}'}?label=join_community&url=https%3A%2F%2Fdiscord.gg%2F...
        </div>
        <p className="text-sm text-zinc-300 leading-relaxed">
          When the recipient clicks the link:
        </p>
        <ol className="list-decimal pl-5 space-y-1.5 text-xs text-zinc-400">
          <li>The request hits the Postly click handler at <code>/api/track/click/[emailId]</code>.</li>
          <li>Postly records a row in the <code>ClickEvent</code> table with: timestamp, label, IP address, and User-Agent.</li>
          <li>The <code>Email</code> record increments its <code>clickCount</code> counter.</li>
          <li>A <code>302 Found</code> HTTP redirect sends the recipient to the original destination URL instantly with zero perceptible latency.</li>
        </ol>
      </section>
    </div>
  );
}

export function CertificatesSection() {
  return (
    <div className="space-y-8">
      <div>
        <div className="flex items-center gap-2 mb-2">
          <span className="text-[11px] font-mono uppercase tracking-wider text-purple-400 font-bold px-2 py-0.5 rounded bg-purple-500/10 border border-purple-500/20">
            Studio & Content
          </span>
          <span className="text-xs text-zinc-500">•</span>
          <span className="text-xs text-zinc-400">PDF Generator</span>
        </div>
        <h1 className="text-3xl font-extrabold text-white tracking-tight">Certificate Studio (PDF)</h1>
        <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
          Postly&apos;s Certificate Studio at <code>/certificates</code> empowers you to generate high-resolution, personalized PDF certificates and diplomas at scale with coordinate-based field mapping and dynamic QR verification badges.
        </p>
      </div>

      <div className="h-px bg-zinc-800/80" />

      {/* What is Certificate Studio */}
      <section id="certificate-studio-intro" className="space-y-4 scroll-mt-24">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <Award className="h-5 w-5 text-amber-400" />
          What is Certificate Studio?
        </h2>
        <p className="text-sm text-zinc-300 leading-relaxed">
          Rather than manually editing templates in design software or exporting hundreds of documents by hand, Certificate Studio lets you upload an existing PDF base template and define dynamic text and QR overlays. During a campaign, Postly generates an individualized PDF for each recipient and automatically attaches it to their email.
        </p>
      </section>

      {/* Template Creation */}
      <section id="template-creation-steps" className="space-y-4 scroll-mt-24">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <FileText className="h-5 w-5 text-primary" />
          Creating a Certificate Template
        </h2>
        <div className="space-y-2 text-xs">
          {[
            { step: "1. Upload Base PDF", desc: "Upload your blank certificate design (letter or A4 landscape/portrait) at /certificates." },
            { step: "2. Define Text Fields", desc: "Add dynamic placeholders: {{name}}, {{issue_date}}, {{course_title}}, {{cert_id}}." },
            { step: "3. Configure Styling", desc: "Set font size (e.g. 32px), color hex (#1a365d), weight (Bold), and alignment (Center/Left)." },
            { step: "4. Position Coordinates", desc: "Drag or specify exact X and Y coordinates on the live PDF canvas." },
            { step: "5. Add QR Verification Badge", desc: "Optionally embed a dynamic QR code that links to an authentic verification page." }
          ].map((s, i) => (
            <div key={i} className="flex gap-3 items-start rounded-lg border border-zinc-800 bg-zinc-950 p-3">
              <span className="font-mono font-bold text-primary shrink-0">{s.step}</span>
              <span className="text-zinc-400">{s.desc}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Bulk Generation */}
      <section id="bulk-certificate-generation" className="space-y-4 scroll-mt-24">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <Layers className="h-5 w-5 text-emerald-400" />
          Bulk PDF Generation & Attachment
        </h2>
        <p className="text-sm text-zinc-300 leading-relaxed">
          When you link a Certificate Template to a Bulk Campaign, Postly&apos;s serverless vector PDF engine (<code>pdf-lib</code>) processes each recipient row in memory, bakes the custom fonts and fields directly into a standalone PDF buffer, and names it (e.g. <code>Certificate_Sophia_Chen.pdf</code>) as an email attachment.
        </p>
      </section>
    </div>
  );
}
